wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.31
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.0
batch_size:
  desc: null
  value: 20
epochs:
  desc: null
  value: 500
